name = "BiometricTables"
uuid = "34d2ceec-3238-40bc-9c68-5d5652a6b700"
authors = ["thfreud <thfreud@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
